/*
 * Copyright (c) 2018, Ankit R Gadiya
 * BSD 3-Clause License
 *
 * Project Euler
 *
 * Problem 2: Even Fibonacci numbers
 *
 * Q. Each new term in the Fibonacci sequence is generated by adding the
 *    previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *    By considering the terms in the Fibonacci sequence whose values do not
 *    exceed four million, find the sum of the even-valued terms.
 */
#include <stdio.h>
#include <math.h>

int sumEvenFib(int limit);

int main(void)
{
	printf("%d\n", sumEvenFib(4000000));

	return 0;
}

int sumEvenFib(int limit)
{
	if (limit == 0 || limit == 1)
		return limit;

	float phi_3 = powf(((1 + sqrt(5)) / 2), 3);
	int a = 2, fibSum = 0;

	while (a < limit) {
		fibSum += a;
		a = round(a * phi_3);
	}

	return fibSum;
}
