"""
Copyright (c) 2018, Ankit R Gadiya
BSD 3-Clause License

Project Euler

Problem 2: Even Fibonacci numbers

Q. Each new term in the Fibonacci sequence is generated by adding the previous
   two terms. By starting with 1 and 2, the first 10 terms will be:

   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not
   exceed four million, find the sum of the even-valued terms.
"""


def sumEvenFib(limit):
    if limit is 0 or limit is 1:
        return limit

    phi_3 = (((1 + (5 ** (1 / 2))) / 2) ** 3)
    a = 2
    fibSum = 0

    while a < limit:
        fibSum += a
        a = round(a * phi_3)

    return fibSum


if __name__ == '__main__':
    print(sumEvenFib(4000000))
