; Copyright (c) 2018, Ankit R Gadiya
; BSD 3-Clause License
;
; Project Euler
;
; Problem 2: Even Fibonacci numbers
;
; Q. Each new term in the Fibonacci sequence is generated by adding the
;    previous two terms. By starting with 1 and 2, the first 10 terms will be:
;
;    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
;    By considering the terms in the Fibonacci sequence whose values do not
;    exceed four million, find the sum of the even-valued terms.

(define (sumEvenFib limit)
        (define phi-3 (expt (/ (+ 1 (sqrt 5)) 2) 3))
        (define (iter a fibSum)
                (if (> a limit)
                    fibSum
                    (iter (round (* a phi-3))
                          (+ a fibSum))))
        (if (< limit 2)
            limit
            (iter 2 0)))

(sumEvenFib 4000000)
